In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
arr2d=np.array([[1,2,3],[4,5,6]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr*2

array([2, 4, 6, 8])

#### this has mulitplied all the elemnets in the arr by 2

In [8]:
arr2=np.arange(100)

In [9]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [10]:
arr3=np.arange(1,100)

In [11]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### this np.arange is used to generate a array from the starting range to ending range

In [18]:
arr0=np.zeros((2,2))

In [19]:
arr0

array([[0., 0.],
       [0., 0.]])

In [20]:
arr1=np.ones((2,2))

In [21]:
arr1

array([[1., 1.],
       [1., 1.]])

## properties of array

In [22]:
arr.shape

(4,)

In [28]:
arr.ndim

1

In [29]:
arr2d.ndim

2

In [30]:
arr1.ndim

2

#### this ndim properties tells the dimensions of an array

In [34]:
arr.size

4

In [35]:
arr2d.size

6

#### this arr.size tells the length(total elements) of an array

## indexing 

In [44]:
arr[1:2]

array([2])

In [45]:
arr2d[1:3,1:3]

array([[5, 6]])

#### to perform indexing on 1d array you perfrom normal indexing like python but to perform indexing on 2d array you perfom indexing like[row_indexing,column_indexing]

## sorting

In [47]:
np.sort(arr)

array([1, 2, 3, 4])

## some operations on array

In [48]:
even=arr[arr%2==0]

In [49]:
even

array([2, 4])

#### this returns a new array that contain even numbers from the array arr

## there is term called fancy indexing in numpy 

In [55]:
index=[1,2]
print(arr[index])

[2 3]


In [58]:
index1=np.where(arr>3)

In [59]:
print(arr[index1])

[4]


In [60]:
index1

(array([3]),)

In [61]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])

In [62]:
a1+a2

array([2, 4, 6])

#### this will add the elements of the two arrays and return an array

In [66]:
a3=np.concatenate((a1,a2))

In [67]:
a3

array([1, 2, 3, 1, 2, 3])

#### to append oen array to anotehr array here we use conacatenate()
